version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "sbf_challenge"
      MYSQL_USER: "app_user"
      MYSQL_PASSWORD: "my_secret"
      MYSQL_ROOT_PASSWORD: "root"
      LANG: C.UTF-8
      TZ: America/Sao_Paulo
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"
