const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./index.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "SBF Challenge",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Products",
      description: "Endpoints",
    },
  ],
  definitions: {
    CurrencyResponse: {
      $name: "Tênis Nike Shox R4",
      $baseValue: 529.99,
      $USDValue: 98.23,
      $EURValue: 83.26,
      $INRValue: 7318.93,
      dateOfRegistration: "2021-08-31 17:05:19",
    },
    ProductBody: {
      $name: "Tênis Nike Shox R4",
      $value: 529.99,
      $inventory: 10,
      $size: "GG",
      $gender: "Masculino",
    },
    ProductToUpdate: {
      name: "Tênis Nike Shox R4",
      value: 699.99,
      inventory: 10,
      size: "GG",
      gender: "Masculino",
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then();
